# Generated by Django 4.0 on 2022-01-03 02:14

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='id',
            field=models.BigAutoField(auto_created=True, default=builtins.id, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officers',
            name='id',
            field=models.BigAutoField(auto_created=True, default=builtins.id, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='officers',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
