# Generated by Django 3.2.8 on 2021-12-13 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisors',
            fields=[
                ('supervisor_id', models.IntegerField(blank=True, null= True, default=0)),
                ('officer_id', models.IntegerField(blank=True, null= True, default=0)),
                ('last_name', models.CharField(max_length=20, blank=True, null= True)),
                ('first_name', models.CharField(max_length=20, blank=True, null= True)),
                ('middle_name', models.CharField(max_length=20, blank=True, null= True)),
                ('badge_number', models.IntegerField(blank=True, null= True, default=0)),
                ('is_active', models.BooleanField(blank=False, null=True))
            ],
        ),
    
        migrations.CreateModel(
            name='SupervisorReport',
            fields=[
                ('supervisor_report_id', models.IntegerField(blank=True, null= True, default=0)),
                ('supervisor_id', models.IntegerField(blank=True, null= True, default=0)),
                ('date', models.DateTimeField(auto_now_add=False)),
                ('total_calls_for_service', models.IntegerField(blank=True, null= True, default=0)),
                ('total_case_numbers_pulled', models.IntegerField(blank=True, null= True, default=0)),
                ('total_case_numbers_completed', models.IntegerField(blank=True, null= True, default=0)),
                ('total_reports', models.IntegerField(blank=True, null= True, default=0)),
                ('total_supplements', models.IntegerField(blank=True, null= True, default=0)),
                ('total_vehicles_assigned', models.IntegerField(blank=True, null= True, default=0)),
                ('total_miles_driven', models.IntegerField(blank=True, null= True, default=0)),
                ('officers_on_road', models.IntegerField(blank=True, null= True, default=0)),
                ('officers_on_desk', models.IntegerField(blank=True, null= True, default=0)),
                ('officers_on_jail_duty', models.IntegerField(blank=True, null= True, default=0)),
                ('officers_on_light_duty', models.IntegerField(blank=True, null= True, default=0)),
                ('officers_out_sick', models.IntegerField(blank=True, null= True, default=0)),
                ('officers_in_training', models.IntegerField(blank=True, null= True, default=0)),
                ('officers_on_vacation', models.IntegerField(blank=True, null= True, default=0)),
                ('officers_assigned_elswhere', models.IntegerField(blank=True, null= True, default=0)),
                ('total_citations_issued', models.IntegerField(blank=True, null= True, default=0)),
                ('total_warnings_issued', models.IntegerField(blank=True, null= True, default=0)),
                ('total_citizen_contacts', models.IntegerField(blank=True, null= True, default=0)),
                ('total_traffic_stops', models.IntegerField(blank=True, null= True, default=0)),
                ('total_arrest_made', models.IntegerField(blank=True, null= True, default=0)),
                ('total_juvenile_contacts', models.IntegerField(blank=True, null= True, default=0))
            ],
        ),
    ]
