# Generated by Django 4.0 on 2022-01-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorreport',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisors',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
