# Generated by Django 3.2.8 on 2021-12-13 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('training', models.CharField(max_length=500, unique=True)),
                ('evaluations', models.FileField(("evaluations"), upload_to='uploads/ThisPC/Documents/', max_length=100)),
                ('service_time', models.IntegerField(blank=True, null= True, default=0)),
                ('awards', models.CharField(max_length=500)),
                ('officer_id', models.IntegerField(blank=True, null= True, default=0)), 
            ],
        ),
        migrations.CreateModel(
            name='OfficerRoles',
            fields=[
                ('is_supervisor', models.BooleanField(blank=False, null=True))
            ],
        ),
    ]
