# Generated by Django 4.0 on 2022-01-03 02:14

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='evaluations',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='service_time',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='training',
        ),
        migrations.RemoveField(
            model_name='officerroles',
            name='is_supervisor',
        ),
        migrations.AddField(
            model_name='extra',
            name='id',
            field=models.BigAutoField(auto_created=True, default=builtins.id, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officerroles',
            name='id',
            field=models.BigAutoField(auto_created=True, default=builtins.id, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
